# Further potential for bias: who drops out and who volunteers?

Marie is evaluating a phonological awareness training package with a group of 'at risk' five-year-olds. She has adopted a randomised controlled design, with an active control group who get extra help with maths. She recruits 30 children to each group and runs the intervention for six weeks. However, two weeks in to the study, three children in the phonological awareness group and one from the control group drop out, and she learns that another child from the control group has been taken by his mother for intensive private speech and language therapy which includes phonological awareness training. Marie is left unsure what to do? Should she exclude these children from her study?

## Dealing with dropouts: Intention to treat analysis

Every information sheet for an intervention study emphasises that participants are free to drop out at any time, without giving a reason, with no adverse consequences. This is as it should be: it would not be ethical to compel people to take part in research, and it would be foolish to try. Nevertheless, every researcher's heart sinks when this happens because it can really mess up a trial and make it harder to show an intervention effect.

If Marie were to consult a statistician, she would get an answer that might surprise you. She should not exclude participants who drop out or start other interventions. If people have withdrawn from the study, then their data cannot be included, but if there are children who are willing to be seen for the outcome assessments, their data should be included, even if they did not do the intervention they were assigned as planned. At first glance, this seems crazy. We want to evaluate the intervention: surely we should not include people who don't get the full intervention! Even worse, the control group are supposed to contain people who didn't get the intervention – if we include some who obtained it by other means, this reduces the chances of seeing an effect.

The problems posed by drop-outs may be illustrated with an extreme example. Suppose Bridget Jones volunteers for a study of a miracle cure for fatness that involves giving up regular food for six weeks and consuming only a special banana milkshake that provides 500 calories per day. The control group consists of people who want to lose weight but are just given written materials explaining the calorie content of food. At the end of the six weeks, only 5 of the 50 original milkshake group are sticking to the diet, but they have all lost impressive amounts of weight compared to the control group, whose weight has gone down marginally. Bridget, together with 90% of the intervention group, found the diet impossible to stick to, got so hungry that she binged on chocolate, and actually gained weight. Is it reasonable to conclude that the milkshake diet worked? It depends on what question you are asking. If the question is 'does extreme calorie restriction lead to weight loss?' the answer would appear to be yes. But that's not really what the study set out to do. It was designed to ask whether this specific intervention was effective for the kind of people enrolled in the study. Clearly, it wasn't – and it would be a bad idea to roll this out to larger samples of people. 

In more realistic scenarios for SLTs, interventions are not likely to be so unacceptable to large numbers, but a key point is that drop-outs are seldom random. There are two opposite reasons why someone might give up on an intervention: they may just find it too hard to continue – and this could be because of difficulties in finding the time as much as difficulties with the intervention itself – or they might decide they are doing so well that they no longer need it. Either way, the group left behind after drop out is different from the one we started with.

It's instructive to look at the results from the little study I did using computerised tasks to train comprehension and spelling in children (Chapter x). Teachers and teaching assistants did the exercises with the children, three of whom dropped out. When I looked at the data, I foud that the drop-outs had particularly low comprehension scores at the baseline. It is likely that these children just found the exercises too hard and became dispirited and unwilling to continue. Importantly, they were not a random subset of children. If I had excluded them from the analysis, I would no longer be comparing randomised groups who had been comparable at baseline – I would be comparing an intervention group that now omitted those with the worst problems with a control group that had no such omissions.

Nevertheless, if we only do an 'intention-to-treat' analysis, then we lose an opportunity to learn more about the intervention. I would always complement it with an analysis of the drop-outs. Did they look different at baseline? Do we know why they dropped out? And what were their outcomes? For my comprehension study, this analysis gave a salutary message. The drop-outs showed substantial improvement on the outcome comprehension test, providing a clear example of how scores can change with practice on the test and regression to the mean (see Chapter x). 

## Who volunteers for research?

Many people who might benefit from interventions never take part in research evaluations. It has been noted that in psychological research, there is a bias for participants to be WEIRD, that is Western, educated, and from industrialized, rich, and democratic countries. I am not aware of specific studies on participants in SLT intervention studies, but it is likely that similar biases operate. It is important to know about the demographics of participants, as this may affect the extent to which results will be generalizable to the population at large. Researchers should report on the distribution of socio-economic, educational and ethnic background of those taking part in intervention studies.

If the aim is to evaluate intervention targeted at disadvantaged groups, then it is important to think hard about how to optimise recruitment. Positive moves might include having a researcher or other intermediary who comes from a similar background to the target population, who will  know the best ways to communicate and gain their confidence. Running a focus group may give insights into barriers to participation, which may be practical (finding time, or costs for transport of childcare) or social (feeling uncomfortable around people from a different social or ethnic background). Small things can make a big impact:  one study with disadvantaged families that involved parent-training ended with parents being given a certificate on completing the training: the researchers said that this was appreciated by many parents, most of whom had never obtained any formal qualifications. Some of them went on to help recruit and train the next parent group.

## Class exercise

Download a copy of the CONSORT flow diagram: http://www.consort-statement.org/consort-statement/flow-diagram
Use of this kind of diagram has become standard in medical trials, because it helps clarify the issues covered in this chapter. 
Find an intervention study in the published literature which does not include a flow diagram, and see how much of the information in the flow chart can be completed by reading the Methods section.  
