# Avoiding waste: reviewing the literature before you start

A research report typically starts with an introduction that reviews relevant literature to provide context for the current study. It should establish what work has been done before on this topic, how much we already know, and what gaps there are in our knowledge. Unfortunately, as noted in Chapter 19, many researchers are quite biased in how they review prior literature, typically showing bias in favour of work that supports their own viewpoint. In addition, we often see distortions creeping in wheneby studies are cited in a misleading fashion, perhaps de-emphasising inconvenient results. 

If we accept that science should be cumulative, it is important not to disregard work that reports results that are ambiguous or inconsistent with our position, but we are often victims of our own cognitive biases that encourage us to disregard inconvenient facts. 

Sometimes, a failure to take note of prior work can lead to wasted research funds, if studies are designed to address questions to which the answer is already known [@chalmers2014]. In the field of speech and language therapy, where there is a shortage of published intervention research, this is unlikely to be so much of a problem. In 2004, @law2004 attempted to carry out a meta-analysis to evaluate the effectiveness of intervention for children with developmental speech and language delay/disorder. Over a 25 year period, they found only 25 articles with randomized controlled designs that provided sufficient information for inclusion in a meta-analysis, and the interventions used in these were quite disparate, making it difficult to combine results in a meta-analysis. Although there has been some progress in the past two decades, intervention reports are still fairly rare, and few interventions could be regarded as having such a solid body of evidence in support that further studies are unnecessary.  

Nevertheless, it is important to take into account prior literature when planning an intervention study, yet, as @chalmers2014 noted, this is often not done. We discuss here the gold standard approach to appraising prior literature, the systematic review, and consider how feasible it is for speech and language therapy interventions, and what alternatives might be possible.  


## What is a systematic review?

The strictest definition of a systematic review in clinical research, according to the Cochrane collaboration, is as follows: 

> A systematic review attempts to identify, appraise and synthesize all the empirical evidence that meets pre-specified eligibility criteria to answer a specific research question. Researchers conducting systematic reviews use explicit, systematic methods that are selected with a view aimed at minimizing bias, to produce more reliable findings to inform decision making. - [@cochrane_2020]

The most important part of this definition is the requirement of a 'prespecified eligibility criteria', as many systematic reviews do not conform to such specific criteria following a peer-reviewed protocol and are still badged 'systematic' regardless [@cochrane_2020]. The idea behind the protocol element allows the review to be replicated or updated for a different time period. Beyond clinical resarch, the protocol can be defined and pre-registered (see Chapter 19) and then referred to in the final published systematic review. This ensures the replicability of the review and ensures that search terms are fixed (in the case that search terms are needed to be adjusted, this can be done transparently in the write up).

## Why conduct a literature review?

The primary focus of any literature review at the start of any research project is to survey the research landscape and use this bigger picture outlook to better frame the reseach question of interest (Are we asking the right question?). 

The procedural steps of the literature review are [@Hemingway_2009]:

 - identify all relevant published and unpublished evidence on the research question of interest

 - selection of studies following protocol's inclusion criteria

 - assess the quality of each study included

 - organise, summarise, and unbiasedly present the findings from all included studies
 
 The key points we must take note of and recognise their importance is the presentation of the amalgamated findings in an unbiased way. Regardless of the predisposition of the researcher to the research question of interest, the evidence must be looked at in an objective way and used to inform the study design in a pragmatic way. For example, if the literature review has a mixed boy of evidence for a specific question, then the hypotheis may need to be much more conservative when deciding on effect sizes of interest and variance estimates in the data. Alternatively, if a research question has been well explored and there is a large consensus on an effect that is backed up by robust and replicable results, perhaps the question does not benefit from another study in this area. Another reason might be to assess how feasible an intervention might be to implement.
 
## Systematic review or literature review?

@Kysh_2013 highlights the critical differences between a formal systematic review and a literature review. A literature review is less structured and focuses on qualitative appraisal of either a general topic or specific question in the literature, providing an overview. A systematic review is very specific to a particular research question and will often incorporate a meta-analytic procedure (although not a requirement). The time line for the systematic review is typically quite long (months to years) as all relevant databases must be searched and strictly pre-defined protocols followed. Systematic reviews are a subset of literature reviews and those including meta-analyses are a further subset within systematic reviews (considered the most evidenced based and unbiased). A well-executed systematic review is considered to be one of the most reliable sources of evidence beyond the RCT.    

 
 
